services:
  postgres-odoo-base-15-01:
    container_name: postgres_odoo-base-15-01
    image: postgres:10-alpine
    platform: linux/arm64
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /data/postgres
    volumes:
      - cntt15_01_db:/data/postgres
    ports:
      - "5431:5432"

volumes:
  cntt15_01_db:
